name: CI/CD to EKS

on:
  push:

env:
  AWS_REGION: eu-central-1
  ECR_REPO: finalproject-ivolve-repo
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: v${{ github.run_number }}

jobs:

  terraform:
    name: provide infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

  build-scan-push:
    needs: terraform
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./App
          file: ./App/Dockerfile
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

  update-deployment-file:
    name: Update deployment.yaml in another repo
    needs: build-scan-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: MennaHamouda/ivolve_project/manifests
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          path: repo

      - name: Update image version in deployment.yaml
        run: |
          cd repo/manifests/kubernetes
          sed -i "s|image:.*|image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}|" deployment.yml

      - name: Commit and push changes
        run: |
          cd repo/
          git config user.name "MennaHamouda"
          git config user.email "mennahamouda2002@gmail.com"
          git add .
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push

  
