name: CI/CD to EKS

on:
  push:

env:
  AWS_REGION: eu-central-1
  ECR_REPO: finalproject-ivolve-repo
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: v${{ github.run_number }}

jobs:

  build-scan-push:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

  update-deployment-file:
    name: Update deployment.yaml in another repo
    needs: build-scan-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: MennaHamouda/ivolve_project
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          path: repo

      - name: Update image version in deployment.yaml
        run: |
          cd repo/manifests/overlays/prod
          sed -i "s|image:.*|image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}|" image-patch.yaml

      - name: Commit and push changes
        run: |
          cd repo/
          git config user.name "MennaHamouda"
          git config user.email "mennahamouda2002@gmail.com"
          git add .
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push

  notify-slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: [build-scan-push, update-deployment-file]
    if: always()
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Pipeline Status:\n- Build & Scan: *${{ needs.build-scan-push.result }}*\n- Update Deployment: *${{ needs.update-deployment-file.result }}*\n\nImage Tag: `${{ env.IMAGE_TAG }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
